require("options")
require("plugins")
require("colorscheme")
require("keymaps")
require("completion")
require("dictionary")
require("lualine_config")
-- require("languageTools")
require("lsp")
require("treesitter")
